version: "3.9"
services:
  student-service:
    build: ./services/student-service
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  tasks-service:
    build: ./services/tasks-service
    ports:
      - "4002:4002"
    environment:
      - PORT=4002

  auth-service:
    build: ./services/auth-service
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - JWT_SECRET=campus-life-secret

  notification-service:
    build: ./services/notification-service
    ports:
      - "4004:4004"
    depends_on:
      - tasks-service
    environment:
      - PORT=4004
      - TASKS_SERVICE_URL=http://tasks-service:4002

  campus-service:
    build: ./services/campus-service
    ports:
      - "4005:4005"
    environment:
      - PORT=4005

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - student-service
      - tasks-service
      - auth-service
      - notification-service
      - campus-service
    environment:
      - PORT=4000
      - STUDENT_SERVICE_URL=http://student-service:4001
      - TASKS_SERVICE_URL=http://tasks-service:4002
      - AUTH_SERVICE_URL=http://auth-service:4003
      - NOTIFICATION_SERVICE_URL=http://notification-service:4004
      - CAMPUS_SERVICE_URL=http://campus-service:4005
